id: P009366
initial_creation_type: ocr
source_metadata:
  id: bdr:W20442
  title: བོད་ཀྱི་བརྩམས་སྒྲུང་འདེམས་སྒྲིག
  author: ''
  volumes:
    90403ac539fa4810a6dc4b3d94222928:
      image_group_id: I1KG16010
      title: ''
      volume_number: 1
      total_pages: 732
